import {useEffect,useState} from 'react';
import './console.css';
import './broker.css';
import './manager.css';
type Device={id:string;name:string;description:string;createdAt:string;codeExpiresAt:string;claimedAt:string|null;revokedAt:string|null;online:boolean;hostname?:string;platform?:string;broker?:boolean};
type Issued={device:Device;code:string};
export function ManagerApp(){
 const [reachable,setReachable]=useState(false);
 const [devices,setDevices]=useState<Device[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState('');
 const [name,setName]=useState(''),[description,setDescription]=useState(''),[busy,setBusy]=useState(false),[issued,setIssued]=useState<Issued|null>(null);
 const [theme,setTheme]=useState<'dark'|'light'>('dark'),[copied,setCopied]=useState(false);
 useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);
 async function refresh(){const r=await fetch('/api/v1/devices');if(!r.ok)throw Error('Unable to reach the device manager.');const body=await r.json();if(!Array.isArray(body.devices))throw Error('Invalid inventory response.');setDevices(body.devices);setLoaded(true);setReachable(true)}
 useEffect(()=>{let active=true;const tick=()=>{if(active)void refresh().catch(e=>{setReachable(false);setError(e.message)})};tick();const timer=setInterval(tick,5000);return()=>{active=false;clearInterval(timer)}},[]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setCopied(false);try{const r=await fetch('/api/v1/devices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),description})});if(!r.ok)throw Error('Device creation failed.');setIssued(await r.json());setName('');setDescription('');await refresh()}catch(e){setError(e instanceof Error?e.message:'Request failed.')}finally{setBusy(false)}}
 async function action(d:Device,verb:'revoke'|'code'|'delete'){if(!confirm(verb==='delete'?`Permanently delete ${d.name}? Its registration record will be removed. This cannot be undone and does not uninstall software on the device.`:verb==='revoke'?`Revoke ${d.name}? Its enrollment or certificate will no longer be accepted.`:`Replace the enrollment code for ${d.name}? The previous code will stop working.`))return;setBusy(true);setError('');try{const r=await fetch(`/api/v1/devices/${d.id}/${verb}`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error('Device changed or the operation is unavailable.');if(verb==='code'){setIssued(await r.json());setCopied(false)}else if(issued?.device.id===d.id)setIssued(null);await refresh()}catch(e){setError(e instanceof Error?e.message:'Request failed.')}finally{setBusy(false)}}
 function status(d:Device){return d.revokedAt?'Revoked':d.claimedAt?(!reachable?'Unknown':d.online?'Online':'Offline'):Date.parse(d.codeExpiresAt)<=Date.now()?'Code expired':'Awaiting enrollment'}
 const effective=issued&&devices.find(d=>d.id===issued.device.id);
 const codeLive=issued&&(!effective||(!effective.claimedAt&&!effective.revokedAt))&&Date.parse(issued.device.codeExpiresAt)>Date.now();
 return <div className="console-shell"><header className="console-header"><a className="brand" href="/"><img src="/donkeywork.png" alt=""/><span>DonkeyWork<small>DESKTOP</small></span></a><span className="console-label">Fleet manager</span><button onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'Light':'Dark'}</button></header>
 <main className="console-main manager-main"><div className="console-heading"><div><span className="eyebrow accent">YOUR LAB, CONNECTED</span><h1>Devices</h1><p className="manager-muted">Register a device. Give it a name. Bring it into your workspace.</p></div><span className="manager-count">{devices.length} devices</span></div>
 <section className="manager-notice">Internal preview · No user login · Anyone with network access can manage devices.</section>
 <form className="broker-create manager-form" onSubmit={create}><div><h2>Create device</h2><p>Generate a one-time enrollment code, valid for 24 hours.</p></div><label>Device name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Minigpu"/></label><label>Description<input maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Location or purpose"/></label><button disabled={busy||!name.trim()} type="submit">{busy?'Working…':'Create device'}</button></form>
 <section className="manager-notice"><a href="/downloads/dwdesktop-agent-0.1.0-preview6.tar.gz">Download Linux installer (amd64 + arm64)</a> · <a href="/downloads/manager-ca.crt">Preview manager CA</a><p>Install interactively or use --manager URL --code XXXX-XXXX --ca-file manager-ca.crt. Only enrollment and connectivity; desktop sessions are not changed.</p></section>
 {issued&&<section className="manager-enrollment" role="status"><div><span className="eyebrow accent">{issued.device.name}</span><h2>{codeLive?'Ready to enroll':'Code no longer usable'}</h2>{codeLive?<><code data-testid="enrollment-code">{issued.code}</code><p>Expires {new Date(issued.device.codeExpiresAt).toLocaleString()}. Once claimed, it is dead.</p><p>Manager URL: <strong>{window.location.origin}</strong></p><p>This code is shown only now. Pass it to the installer with --code, or use --code-file to keep it out of process arguments.</p></>:<p>The code was claimed, revoked or expired.</p>}</div><div className="console-actions">{codeLive&&<button onClick={()=>void navigator.clipboard.writeText(issued.code).then(()=>setCopied(true)).catch(()=>setError('Clipboard unavailable. Select and copy the code manually.'))}>{copied?'Copied':'Copy code'}</button>}<button onClick={()=>setIssued(null)}>Dismiss</button></div></section>}
 {error&&<p role="alert">{error}</p>}
 {!loaded?<p>Loading devices…</p>:devices.length===0?<section className="broker-empty"><h2>Your fleet starts here</h2><p>Create your first device above. No desktop sessions will be started or changed.</p></section>:<div className="broker-list">{devices.map(d=><article className="broker-card" key={d.id} data-device-id={d.id}><div><h2>{d.name}</h2><p>{d.description||'No description'}</p><span className="manager-device-id">{d.id}</span></div><div className="manager-device-actions"><span className="manager-state" data-state={status(d).toLowerCase()} title={status(d)==='Online'?'Authenticated device connection; heartbeat received within 45 seconds':undefined}><span className="manager-state-dot" aria-hidden="true"/>{status(d)}</span>{!d.revokedAt&&d.claimedAt&&(reachable&&d.online&&d.broker?<a className="manager-open-desktops" href={`/?device=${d.id}&managed`}>Open desktops</a>:<button disabled title={!reachable?'Manager connection unavailable':!d.online?'Device is offline':'Session broker is not configured on this device'}>Open desktops</button>)}{!d.revokedAt&&!d.claimedAt&&<button disabled={busy} onClick={()=>void action(d,'code')}>New code</button>}{!d.revokedAt&&<button disabled={busy} onClick={()=>void action(d,'revoke')}>Revoke</button>}{d.revokedAt&&<button disabled={busy} onClick={()=>void action(d,'delete')}>Delete</button>}</div></article>)}</div>}
 <footer className="console-status">Certificate-authenticated device connectivity · Session broker available on configured pilot hosts.</footer></main></div>
}
